### PR TITLE
Create Basedb class to wrap db object

### PR DESCRIPTION
**Pull request by ghost**
### What was wrong?
Another attempt to create the BaseDB wrapper

### How was it fixed?
Created a class to get early feedback if in right direction

#### Cute Animal Picture
IOU

> put a cute animal picture here.

### CODE REVIEW

**Comment by ghost** [comment]
@gsalgado Am I on the right track this time?

Would appreciate if you could explain what the DB object is in the first place.  It might help me make more sense of the task.

**Comment by gsalgado** [comment]
@egong the _BaseDB_ I referred to is the one in evm/db/backends/base.py

**Comment by ghost** [comment]
@gsalgado trying again with this latest commit.  please walk me through more if I'm not understanding properly, thanks.  would love to reach success on this task.

**Comment by gsalgado** [comment]
Sorry, @egong, I don't have the time to help you with this. I suggest you create the PR on the upstream repo as maybe somebody else would be able to help you

**Pull request closed without merging**
